TodoList.MVC/Models/ErrorViewModel.cs
namespace TodoList.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TodoList.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TodoList.MVC.Models;

namespace TodoList.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Visited the Home Page!");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TodoList.MVC/Controllers/TodoListController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.BLL.Interfaces;

namespace TodoList.MVC.Controllers
{
    public class TodoListController : Controller
    {
        private readonly IUserService _userService;

        public TodoListController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            var model = _userService.GetUsersWithTasks();

            return View(model);
        }
    }
}

TodoList.MVC/Pages/TodoList/Index.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

TodoList.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@section Scripts
{
    <script>alert("Hello");</script>
}

TodoList.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]- TodoList.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TodoList.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TodoList.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoList" asp-action="Index">TodoList</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TodoList.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TodoList.MVC/Views/TodoList/Index.cshtml
@model IEnumerable<TodoList.BLL.Models.UserWithTaskVM>

@foreach (var item in Model.Select((value, i) => new{ value, i}))
{
    <h4>@(item.i + 1). @item.value.Fullname's Tasks</h4>
    <table class="table table-striped">

        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Task</th>
            <th scope="col">Description</th>
            <th scope="col">Priority</th>
            <th scope="col">Due date</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>

        @{
            foreach (var task in item.value.Tasks.Select((value, i) => new{ value, i}))
            {
                <tr>
                    <th scope="row">@(task.i + 1)</th>
                    <td>@task.value.Title</td>
                        <td>@task.value.Description</td>
                        <td>@task.value.Priority</td>
                        <td>@task.value.DueDate</td>

                        <td>@task.value.Status</td>

                </tr>
            }
        }




        </tbody>
    </table>

}